version: 0.0
Resources:
 - TargetService:
     Type: AWS::ECS::Service
     Properties:
       TaskDefinition: arn:aws:ecs:eu-west-1:761081309080:task-definition/webappBG8082:1
       LoadBalancerInfo:
         ContainerName: webappBG8082
         ContainerPort: 80