version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "761081309080"
    IMAGE_REP_NAME: "mywebapp-ngnix"
    IMAGE_TAG: "latest"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 761081309080.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t mywebapp-ngnix:latest .
      - docker tag mywebapp-ngnix:latest 761081309080.dkr.ecr.eu-west-1.amazonaws.com/mywebapp-ngnix:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 761081309080.dkr.ecr.eu-west-1.amazonaws.com/mywebapp-ngnix:latest